### ISSUE TITLE
[product] Fonetic hyper local

### ISSUE THREAD

**Issue by montarion** [Fonetic-studio/fonetic#10]
This issue is to prepare the development of the 'hyper local' product, that serves as "an updated town square".

# Goals
- [ ] A digital space (linked to a geographical location) exists for users to communicate
- [ ] Users can post and respond to (initially) text messages
- [ ] Users are authenticated
- [ ] Users are authorized based on identity and proximity to the geographical location
 
# Requirements
- [ ] User data never leaves the system
- [ ] User data is encrypted at rest
- [ ] The system has some form of anti-theft/tamper protection, e.g a full wipe after leaving a geo-fenced area, or inability to reach a certain server
- [ ] At system setup, the level of identification can be set, e.g. full name, first name only, last name only, home address verification, membership verification (for example, at a library)
- [ ] Users can interface with the system using a mobile webbrowser
- [ ] Users can _only_ interface with the system when in proximity to the geographical location.
# Tasks
